api_key: "your openai api key"
max_tokens: 1000
YourAppPath: /path/to/new_project/build/Build/Products/Debug-iphonesimulator/new_project.app
iPhone: iPhone 14
test_regime: /path/to/new_project/ios_app_rapid_test.sh
model_id: gpt-4
